global:
  scrape_interval: 10s 
  scrape_timeout: 10s


scrape_configs:


  - job_name: 'xyne-data-ingest'


    metrics_path: /prometheus/v1/values


    static_configs:
      - targets: ['vespa:8080']
